<a href="https://colab.research.google.com/github/Razvi103/CIFAR10-Image-Classification/blob/main/cifar10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Conv2D, Dropout, MaxPooling2D, Input, BatchNormalization, Flatten
from tensorflow.keras.models import Model


In [ ]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

print(y_test)

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step
[[3]
 [8]
 [8]
 ...
 [5]
 [1]
 [7]]


In [ ]:
i = Input(shape=x_train[0].shape)
x = Conv2D(32, (3, 3), activation='relu', padding='same')(i)
x = BatchNormalization()(x)
x = Conv2D(32, (3, 3), activation='relu', padding='same')(x)
x = BatchNormalization()(x)
x = MaxPooling2D(2, 2)(x)
x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = BatchNormalization()(x)
x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = BatchNormalization()(x)
x = MaxPooling2D(2, 2)(x)
x = Conv2D(128, (3, 3), activation='relu', padding='same')(x)
x = BatchNormalization()(x)
x = Conv2D(128, (3, 3), activation='relu', padding='same')(x)
x = BatchNormalization()(x)
x = MaxPooling2D(2, 2)(x)

x = Flatten()(x)
x = Dropout(0.2)(x)
x = Dense(512, activation='relu')(x)
x = Dropout(0.2)(x)
x = Dense(1024, activation='relu')(x)
x = Dropout(0.2)(x)
x = Dense(10, activation='softmax')(x)

model = Model(i, x)



In [ ]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=50)

Epoch 1/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 32s 12ms/step - accuracy: 0.4131 - loss: 1.6724
Epoch 2/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.6798 - loss: 0.9227
Epoch 3/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.7488 - loss: 0.7361
Epoch 4/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.7870 - loss: 0.6277
Epoch 5/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8192 - loss: 0.5363
Epoch 6/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.8432 - loss: 0.4642
Epoch 7/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.8641 - loss: 0.4043
Epoch 8/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.8765 - loss: 0.3682
Epoch 9/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8925 - loss: 0.3189
Epoch 10/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8989 - loss: 0.2943
Epoch 11/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9120 - loss: 0.2590
Epoch 12/50
1563/1563 ━

In [ ]:
batch_size = 32
data_generator = tf.keras.preprocessing.image.ImageDataGenerator(width_shift_range= 0.1, height_shift_range=0.1, rotation_range=0.2)
train_generator = data_generator.flow(x_train, y_train, batch_size)
steps_per_epoch = x_train.shape[0] // batch_size
model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch,
    epochs=50
)

Epoch 1/50
   1/1562 ━━━━━━━━━━━━━━━━━━━━ 4:48 185ms/step - accuracy: 0.8125 - loss: 1.3681

/usr/local/lib/python3.10/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


1562/1562 ━━━━━━━━━━━━━━━━━━━━ 38s 24ms/step - accuracy: 0.8518 - loss: 0.4852
Epoch 2/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 0s 12us/step - accuracy: 0.9375 - loss: 0.1740
Epoch 3/50
   1/1562 ━━━━━━━━━━━━━━━━━━━━ 4:06 158ms/step - accuracy: 0.9062 - loss: 0.2979

/usr/lib/python3.10/contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)


1562/1562 ━━━━━━━━━━━━━━━━━━━━ 39s 25ms/step - accuracy: 0.8822 - loss: 0.3671
Epoch 4/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 0s 6us/step - accuracy: 0.8750 - loss: 0.3726  
Epoch 5/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 37s 24ms/step - accuracy: 0.8865 - loss: 0.3404
Epoch 6/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 0s 5us/step - accuracy: 0.8750 - loss: 0.2760 
Epoch 7/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 41s 24ms/step - accuracy: 0.8914 - loss: 0.3270
Epoch 8/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 0s 6us/step - accuracy: 0.8438 - loss: 0.4287 
Epoch 9/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 38s 24ms/step - accuracy: 0.8954 - loss: 0.3108
Epoch 10/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 0s 6us/step - accuracy: 0.9062 - loss: 0.4210 
Epoch 11/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 41s 24ms/step - accuracy: 0.9028 - loss: 0.2929
Epoch 12/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 0s 6us/step - accuracy: 0.8438 - loss: 0.3725  
Epoch 13/50
1562/1562 ━━━━━━━━━━━━━━━━━━━━ 38s 24ms/step - accuracy: 0.9047 - loss: 0.2858
Epoch 14/50
1562/156

In [ ]:
y_pred = model.predict(x_test).argmax(axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix


accuracy = accuracy_score(y_pred=y_pred, y_true=y_test)
cm = confusion_matrix(y_pred, y_test)
print(accuracy)
print(cm)

0.8592
[[926   4  57  29  21  10   6  16  49  19]
 [ 11 977   4   6   2   6   2   4  22  93]
 [ 11   0 756  27  24  14  13  11   4   2]
 [  6   1  40 763  37 115  29  25   4   1]
 [  4   2  38  31 849  28   9  35   0   0]
 [  1   0  29  74  11 769   1  31   1   3]
 [  2   0  57  39  40  30 932   9   5   4]
 [  4   0  11   9  12  19   1 860   0   2]
 [ 22   5   3  12   1   3   5   2 900  16]
 [ 13  11   5  10   3   6   2   7  15 860]]
